name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source Git branch
          uses: actions/checkout@v3
          with:
            ref: master
            fetch-depth: 10
            submodules: true
            
        - name: Compile CSS from SCSS files
          uses: gha-utilities/sass-build@v0.4.11
          with:
            source: styles/styles.scss
            destination: styles/styles.css
  
        - name: Add and Commit changes to pr-pages branch
          run: |
            git config --local user.email 'action@github.com'
            git config --local user.name 'GitHub Action'
            git add styles/*
            git commit -am 'Updates compiled CSS files'
  
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: master
  
