name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source Git branch
          uses: actions/checkout@v3
          with:
            ref: master
            fetch-depth: 10
            submodules: true
              
        - name: Make destination directory for compiled CSS
          run: mkdir -vp /tmp/assets/css

        - name: Compile CSS from SCSS files
          uses: gha-utilities/sass-build@v0.4.11
          with:
            source: /styles/styles.scss
            destination: /tmp/assets/css/main.css
