name: Deploy

on:
  push:
    branches:
      - master

build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source Git branch
          uses: actions/checkout@v2
          with:
            ref: main
            fetch-depth: 10
            submodules: true

        - name: Sass Build
          uses: gha-utilities/sass-build@v0.4.11
          with:
              source: /styles/styles.scss
              destination:  /styles/styles.css
